---
title: "big_mac"
author: "Alex Doyle"
date: "2/15/2021"
output: html_document
---

```{r cars}
big_mac<- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-12-22/big-mac.csv')

```
```{r}
library(tidyverse)
library(ggdark)
library(ggflags)
```


```{r}
eda <- big_mac %>%
  group_by(date) %>%
  summarise(
  value = max(dollar_price))

eda1 <- big_mac %>%
  group_by(date) %>%
  summarise(
    value = min(dollar_price)
  ) 

eda <- cbind(condition = "max", eda)
eda1 <- cbind(condition = "min", eda1)

eda <- rbind(eda, eda1)
```


```{r} 
col1 <- "#ccd5ae" # neutral colour  faedcd ccd5ae
col2 <- "white"
bg <- "black"


wd <- 80
title <- "The Big Mac index"
subtitle0 <- str_wrap(
  "The income gap between White and Black American middle income earners between
  1967 and 2019",
  wd)
subtitle1 <- str_wrap(
  '"Income is money coming into a family, while wealth is a family’s assets—things like savings"',
  wd)

subtitle <- paste(subtitle0, "\n\n", subtitle1)




main <- eda %>%
  group_by(condition) %>%
  ggplot( aes(x = date, y = value, fill = condition)) + 
   geom_bar(stat = "identity", position = "identity")+
   coord_cartesian(clip = "off") +
  scale_fill_manual(values = c("#00AFBB", "black")) +
  dark_theme_classic() +
  theme(
    plot.background = element_rect(fill = bg),
    plot.margin = margin(l = 20, t = 70, r = 80),
    legend.position = "none",
    plot.caption = element_text( colour = col1, margin = margin(b = 20), size = 12)
  )

title <- ggplot() +
  geom_text(aes(x = 0.1, y = .57), label = title, colour = col1, size = 8, hjust = 0) +
  
  theme_void() +
  theme(
    plot.background = element_rect(fill = NA)
  ) +
  coord_cartesian(clip = "off", xlim = c(0, 1), ylim = c(0, 1)) + 
  #annotate("text", x = 18, y = 0.04, label = "}", size = 10, col = "#00AFBB") +
  annotate("text", x = 4, y = 0.27, label = "Overvalued", size = 3.5, col = "#00AFBB") +
  #annotate("text", x = 18, y =  -0.12, label = "}", size = 10, col = "#D71919") +
  annotate("text", x = 4, y = -0.285, label = "Undervalued", size = 3.5, col = "#D71919")







text <- ggplot() +
  geom_text(aes(x = 0.1, y = 0.1), label = subtitle,  colour = col1, size = 3, hjust = 0) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = NA)
  ) +
  coord_cartesian(clip = "off", xlim = c(0, 1), ylim = c(0, 1))

ggdraw() +
  draw_plot(main) +
  draw_plot(text, 0.6, 0.75, .001, 0.01) + 
  draw_plot(title, 0.03, 0.35, 0.05, 1.0)
```
```{r}
value1 <- abs(rnorm(26))*2
data <- data.frame(
  x=LETTERS[1:26], 
  value1=value1, 
  value2=value1+1+rnorm(26, sd=1))
```

```{r}
library(viridis)
big_mac %>%
  ggplot( aes(x=date, y=usd_raw, group=, color=name)) +
    geom_line() +
    scale_color_viridis(discrete = TRUE) +
    theme(
      legend.position="none",
      plot.title = element_text(size=14)
    ) +
    ggtitle("A spaghetti chart of baby names popularity") 
```


```{r}

library(tidyverse)
library(tidytuesdayR)
library(extrafont)
library(janitor)
library(glue)
library(cowplot)
library(ggforce)
library(purrr)
library(png)

df <- tt_load(2021, week = 7)


#### fonts ####
ft <- "Verdana Pro Light"
ftb <- "Verdana Pro Black"
#ft <- "Sarabun ExtraLight"
#ftb <- "Sarabun ExtraBold"

#### palette ####
col1 <- "#ccd5ae" # neutral colour  faedcd ccd5ae
col2 <- "white"
bg <- "black"

#### titles ####
wd <- 70
title <- "Income Inequality"
subtitle0 <- str_wrap(
  "The income gap between White and Black American middle income earners between
  1967 and 2019",
  wd)
subtitle1 <- str_wrap(
  '"Income is money coming into a family, while wealth is a family’s assets—things like savings,
  real estate, businesses—minus debt. Both are important sides of families’ financial security,
  but wealth cushions families against emergencies and gives them the means to move up the economic
  ladder. Also, wealth disparities are much greater than income disparities: three times as much by
  one measure."',
  wd)
subtitle2 <- str_wrap(
  '"Income inequality can worsen wealth inequality because the income people have available to save and
  invest matters. Focusing on private income, such as earnings and dividends, plus cash government
  benefits, we see that the income of families near the top increased roughly 90 percent from 1963 to
  2016, while the income of families at the bottom increased less than 10 percent."',
  wd)
subtitle <- paste(subtitle0, "\n\n", subtitle1)

#### plot ####
ann_df <- tibble(
  x = 2022,
  y = c(72471, 45356),
  label = c("White - $72k", "Black - $45k"),
  race = c("Black Alone", "White Alone"),
  difference = 1
)

main <- df$income_mean %>%
  filter(
    dollar_type == "Current Dollars",
    income_quintile == "Middle",
    race %in% c("White Alone", "Black Alone")
    ) %>%
  mutate(race = factor(race, levels = c("White Alone", "Black Alone"))) %>%
  arrange(year, race) %>%
  select(year, race, income_dollars) %>%
  # pivot_wider(names_from = race, values_from = income_dollars) %>%
  # clean_names() %>%
  # mutate(d = 100*round(white_alone/black_alone, 2)) %>%
  group_by(race) %>%
  mutate(difference = ifelse(race == "Black Alone", 1, income_dollars/max(income_dollars))) %>%
  ggplot(aes(x = year, y = income_dollars, fill = race, alpha = difference, colour = NULL)) +
  geom_bar(stat = "identity", position = "identity") +
  geom_text(data = ann_df, mapping = aes(x = x, y = y, label = label), colour = col1, family = ft, size = 5) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg),
    plot.margin = margin(l = 80, t = 40, r = 40),
    legend.position = "none",
    plot.caption = element_text(family = ft, colour = col1, margin = margin(b = 20), size = 12)
  ) +
  labs(
    caption = "Source: Urban Institute and US Census / Graphic: @danoehm"
  ) +
  coord_cartesian(clip = "off") +
  # coord_polar("y", clip = "off") +
  scale_fill_manual(values = c(col1, "black"))

text <- ggplot() +
  geom_text(aes(x = 0.1, y = 0.57), label = title, family = ftb, colour = col1, size = 20, hjust = 0) +
  geom_text(aes(x = 0.1, y = 0.35), label = subtitle, family = ft, colour = col1, size = 5, hjust = 0) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg)
  ) +
  coord_cartesian(clip = "off", xlim = c(0, 1), ylim = c(0, 1))


```

```{r}
wd <- 70
title <- "Income Inequality"
subtitle0 <- str_wrap(
  "The income gap between White and Black American middle income earners between
  1967 and 2019",
  wd)
subtitle1 <- str_wrap(
  '"Income is money coming into a family, while wealth is a family’s assets—things like savings,
  real estate, businesses—minus debt. Both are important sides of families’ financial security,
  but wealth cushions families against emergencies and gives them the means to move up the economic
  ladder. Also, wealth disparities are much greater than income disparities: three times as much by
  one measure."',
  wd)
subtitle2 <- str_wrap(
  '"Income inequality can worsen wealth inequality because the income people have available to save and
  invest matters. Focusing on private income, such as earnings and dividends, plus cash government
  benefits, we see that the income of families near the top increased roughly 90 percent from 1963 to
  2016, while the income of families at the bottom increased less than 10 percent."',
  wd)
subtitle <- paste(subtitle0, "\n\n", subtitle1)

#### plot ####
ann_df <- tibble(
  x = 2022,
  y = c(72471, 45356),
  label = c("White - $72k", "Black - $45k"),
  race = c("Black Alone", "White Alone"),
  difference = 1
)

main <- df$income_mean %>%
  filter(
    dollar_type == "Current Dollars",
    income_quintile == "Middle",
    race %in% c("White Alone", "Black Alone")
    ) %>%
  mutate(race = factor(race, levels = c("White Alone", "Black Alone"))) %>%
  arrange(year, race) %>%
  select(year, race, income_dollars) %>%
  # pivot_wider(names_from = race, values_from = income_dollars) %>%
  # clean_names() %>%
  # mutate(d = 100*round(white_alone/black_alone, 2)) %>%
  group_by(race) %>%
  mutate(difference = ifelse(race == "Black Alone", 1, income_dollars/max(income_dollars))) %>%
  ggplot(aes(x = year, y = income_dollars, fill = race, alpha = difference, colour = NULL)) +
  geom_bar(stat = "identity", position = "identity") +
  geom_text(data = ann_df, mapping = aes(x = x, y = y, label = label), colour = col1, family = ft, size = 5) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg),
    plot.margin = margin(l = 80, t = 40, r = 40),
    legend.position = "none",
    plot.caption = element_text(family = ft, colour = col1, margin = margin(b = 20), size = 12)
  ) +
  labs(
    caption = "Source: Urban Institute and US Census / Graphic: @danoehm"
  ) +
  coord_cartesian(clip = "off") +
  # coord_polar("y", clip = "off") +
  scale_fill_manual(values = c(col1, "black"))

text <- ggplot() +
  geom_text(aes(x = 0.1, y = 0.57), label = title, family = ftb, colour = col1, size = 20, hjust = 0) +
  geom_text(aes(x = 0.1, y = 0.35), label = subtitle, family = ft, colour = col1, size = 5, hjust = 0) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg)
  ) +
  coord_cartesian(clip = "off", xlim = c(0, 1), ylim = c(0, 1))
text
continent <- readr::read_csv('https://datahub.io/JohnSnowLabs/country-and-continent-codes-list/r/0.csv')
```

```{r}
continents <- continent
lolipop <- big_mac %>%
  group_by(date) %>%
   slice( which.max(usd_raw)) %>%
  select(date, iso_a3, usd_raw) %>%
  rename(max_usd = usd_raw, 
         max_code = iso_a3)
  
lolipop2 <- big_mac %>%
  group_by(date) %>%
  slice( which.min(usd_raw)) %>%
  select(date, iso_a3, usd_raw) %>%
  rename(min_usd = usd_raw, 
         min_code = iso_a3)
  
lolipop <- bind_cols(lolipop, lolipop2)

continents <- continents %>%
  clean_names() %>%
  select(two_letter_country_code, three_letter_country_code)%>%
  rename(min_2 = two_letter_country_code, 
         min_code = three_letter_country_code) %>%
  mutate(min_2 = tolower(min_2))

lolipop<- lolipop %>% 
  inner_join(continents, by = c("min_code"))

continents <- continents %>%
  rename(max_1 = min_2, 
         max_code = min_code)

lolipop<- lolipop %>% 
  inner_join(continents, by = c("max_code"))
```

```{r}
ggplot(lolipop) +
  geom_segment( aes(x=date...1, xend=date...1, y=min_usd, yend=max_usd), color="grey") +
  geom_point( aes(x=date...1, y=min_usd), color=rgb(0.2,0.7,0.1,0.5), size=3 ) +
  geom_point( aes(x=date...1, y=max_usd), color=rgb(0.7,0.2,0.1,0.5), size=3 ) +
  geom_flag(y =  , x = 20000401, aes(country = "il"), size = 400) +
  dark_theme_minimal() +
   theme(
    plot.background = element_rect(fill = bg),
    plot.margin = margin(l = 80, t = 40, r = 40),
    legend.position = "none",
    plot.caption = element_text( colour = col1, margin = margin(b = 20), size = 12)
  )

```